### ISSUE TITLE
Fix global variable

### ISSUE THREAD

**Issue by sakren** [Carrooi/Node-GoogleMaps#16]
https://github.com/Carrooi/Node-GoogleMaps/blob/develop/lib/Google.js#L91

**Comment by thecotne** [comment]
it's not global it is declared at line 23
https://github.com/Carrooi/Node-GoogleMaps/blob/develop/lib/Google.js#L23

**Comment by sakren** [comment]
Oh god.. 

Good catch btw, thanks :wink:

**Comment by thecotne** [comment]
i was going to fix it and send pull request
forked .. cloned .. run jshint and it said `✓ 0 errors` then searched for `script` and find out it is not global and it is also use at line 158
https://github.com/Carrooi/Node-GoogleMaps/blob/develop/lib/Google.js#L158
